name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 9 PM -03
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: GuilhermeGors
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, yaml, markdown
          plugin_languages_limit: 5
          plugin_languages_details: percentage
          config_timezone: America/Sao_Paulo
